"  __  ____   ____     _____ __  __ ____   ____
" |  \/  \ \ / /\ \   / /_ _|  \/  |  _ \ / ___|
" | |\/| |\ V /  \ \ / / | || |\/| | |_) | |
" | |  | | | |    \ V /  | || |  | |  _ <| |___
" |_|  |_| |_|     \_/  |___|_|  |_|_| \_\\____|


set runtimepath+=$HOME/.config/vim

runtime settings.vim

runtime functions.vim

runtime keymap.vim

runtime plugin-basic.vim

runtime plugin-extended.vim
